# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'

    filterDeployedArtifacts: true
    javaHomeOption: 'JDKVersion'

- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-X'
    artifactoryResolverService: 'idani25artifactory'
    targetResolveReleaseRepo: 'eytanr-libs-release'
    targetResolveSnapshotRepo: 'eytanr-libs-snapshot'
    artifactoryDeployService: 'idani25artifactory'
    targetDeployReleaseRepo: 'eytanr-libs-release'
    targetDeploySnapshotRepo: 'eytanr-libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    javaHomeOption: 'JDKVersion'


- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'idani25artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'idani25'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true
    vuln: true